baseURL = 'https://rosemill.github.io/blog-ciberseguridad/'
languageCode = 'es'
title = 'Blog Ciberseguridad'
theme = 'tale'

[Params]
    author = 'Rosemill'

[menu]
    [[menu.main]]
        identifier = 'Sobre mí'
        name = 'Sobre mí'
        title = 'Sobre mí'
        url = '/sobreMi/'
        weight = 0
    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        title = 'Posts'
        url = '/posts/'
        weight = 0
