baseURL = 'https://rosemill.github.io/blog-ciberseguridad/'
languageCode = 'en'
title = 'Blog Ciberseguridad'
theme = 'tale'
defaultContentLanguage = "en"

[Author]
    name = "Rosemill"

[menu]
    [[menu.main]]
        identifier = 'About me'
        name = 'About me'
        title = 'About me'
        url = '/aboutMe/'
        weight = 0
    [[menu.main]]
        identifier = 'posts'
        name = 'Posts'
        title = 'Posts'
        url = '/posts/'
        weight = 0
